from __future__ import annotations

import json
import sys
from collections import Counter
from copy import deepcopy
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent
REPO_ROOT = PROJECT_DIR.parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.instruments import compile_instrument_phrase
from src.performance import apply_profile, load_profile


def main() -> None:
    composition = json.loads((PROJECT_DIR / "composition.json").read_text(encoding="utf-8"))
    explicit_tracks = []
    compiled = {}

    for track_name, track in composition["tracks"].items():
        clip = track["sections"]["solo"]
        if clip.get("events"):
            explicit_tracks.append(track_name)
        phrase = deepcopy(clip["instrument_phrase"])
        semantic_events = compile_instrument_phrase(phrase, 4)
        profiled_events, profile_report = apply_profile(
            semantic_events,
            load_profile(clip.get("sound_library_profile", "general_midi")),
        )
        compiled[track_name] = {
            "semantic_events": semantic_events,
            "profiled_events": profiled_events,
            "profile_report": profile_report,
        }

    lead = compiled["lead_guitar"]["profiled_events"]
    rhythm = compiled["rhythm_guitar"]["profiled_events"]
    articulations = Counter(
        articulation
        for event in lead
        for articulation in event.get("articulations", [])
    )
    durations = {round(float(event["duration"]), 3) for event in lead}
    velocities = [int(event["velocity"]) for event in lead]

    if explicit_tracks:
        raise AssertionError(f"explicit event tracks found: {explicit_tracks}")
    if len(lead) != 82:
        raise AssertionError(f"expected 82 semantic lead notes, got {len(lead)}")
    if not rhythm:
        raise AssertionError("semantic rhythm compiler produced no notes")
    if len(durations) < 6:
        raise AssertionError("lead performance has too little duration variation")
    if min(velocities) == max(velocities):
        raise AssertionError("lead performance has no velocity variation")

    print("[PASS] no track uses explicit events")
    print(f"[PASS] lead passed through instrument_phrase: {len(lead)} notes")
    print(f"[PASS] rhythm was regenerated by strumming logic: {len(rhythm)} notes")
    print(f"[PASS] lead duration variants: {len(durations)}")
    print(f"[PASS] lead velocity range: {min(velocities)}..{max(velocities)}")
    print(f"[INFO] inferred lead articulations: {dict(sorted(articulations.items()))}")
    print(
        "[INFO] slides/vibrato: "
        f"{sum(event.get('slide_from_semitones') is not None for event in lead)}/"
        f"{sum(bool(event.get('vibrato')) for event in lead)}"
    )
    print("[PASS] this is an agent-performance reconstruction, not MIDI event replay")


if __name__ == "__main__":
    main()
